-- REMEMBER TO CHANGE THE USERNAME AND/OR PASSWORD
-- THIS HAS TO BE RUN BY AN ADMIN OR AT LEAST A USER WITH THE PERMISSION TO CREATE A ROLE
CREATE USER spamvoid WITH NOSUPERUSER NOCREATEROLE CREATEDB INHERIT LOGIN PASSWORD 'spamvoid';
